/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Accelerate: typeof import('./src/components/Accelerate.vue')['default']
    Transaction: typeof import('./src/components/Transaction.vue')['default']
  }
}
